### ISSUE TITLE
Editor not honoring the vscode-typograf.type setting.

### ISSUE THREAD

**Issue by yrammos** [rusnasonov/vscode-typograf#1]
Using the latest version of VS Code and vscode-typograf on a Mac, I am failing to make `vscode-typograf.type` work. The plugin persistently uses the default (UTF-8) setting and ignores both available alternatives (`"names"` and `"digits"`). My desired effect is shown in the screenshot below. Might this be a bug or am I missing something? Thanks in advance.

![screen shot 2018-10-28 at 12 21 16 pm](https://user-images.githubusercontent.com/1519337/47614691-65af0880-daac-11e8-94c2-3b80d8ea91e4.png)

**Comment by perseus-me** [comment]
I think it's a bug. Thanks for report!
